name: Flask CI

on:
  push:
    branches:
      - main
      - sbranch
  pull_request:
    branches:
      - main
      - sbranch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with coverage
        run: |
          pip install pytest coverage
          coverage run -m pytest
          coverage report --fail-under=50 > coverage.txt
          coverage html
      - name: Save coverage percentage
        run: |
          grep "TOTAL" coverage.txt | awk '{print $4}' > coverage_percentage.txt
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: htmlcov/

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create a build artifact with coverage
        run: |
          mkdir build
          echo "Build completed." > build/build.txt
          echo "Test coverage: $(cat coverage_percentage.txt)" >> build/build.txt
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/
